---
kind: pipeline
type: docker
name: sqlds

platform:
  os: linux
  arch: amd64

services:
  - image: mysql:8.0
    name: "mysql"
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: mysql
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"

steps:
  - name: "test"
    image: golang:1.20
    commands:
      - go test ./...
  - name: "integraiton_tests"
    image: golang:1.20
    environment:
      INTEGRATION_TESTS: "true"
      MYSQL_URL: "mysql:mysql@tcp(mysql:3306)/mysql"
    commands:
      - go test ./...

---
kind: signature
hmac: a87eed3ff4ff31806a1f22daad4f283b9c6b0e4f8a8be84ae611016a7c4ac474

...
