---
kind: pipeline
type: docker
name: sqlds

platform:
  os: linux
  arch: amd64

services:
  - image: mysql:8.0
    name: "mysql"
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: mysql
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"

steps:
  - name: "test"
    image: golang:1.18
    commands:
      - go test ./...
  - name: "integraiton_tests"
    image: golang:1.18
    environment:
      INTEGRATION_TESTS: "true"
      MYSQL_URL: "mysql:mysql@tcp(mysql:3306)/mysql"
    commands:
      - go test ./...

---
kind: signature
hmac: c4bfaa226ef0065a9fdd8b1f460c2e5cd638a6248c4167fdbbee447e30504d02

...
