---
kind: pipeline
type: docker
name: sqlds

platform:
  os: linux
  arch: amd64

services:
  - image: mysql:8.0
    name: "mysql"
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: mysql
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"

steps:
  - name: "test"
    image: golang:1.19
    commands:
      - go test ./...
  - name: "integraiton_tests"
    image: golang:1.19
    environment:
      INTEGRATION_TESTS: "true"
      MYSQL_URL: "mysql:mysql@tcp(mysql:3306)/mysql"
    commands:
      - go test ./...

---
kind: signature
hmac: d47f380c64ff9e498c69d2553d1d3a0751671f73e11d83866590fc4485211641

...
