name: ci
on:
  pull_request:
  push:
    branches:
      - main
permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:26.7@sha256:66aec17cd21a956029b83f083b813073859e8355dc1a00e55df6ba02f0e32345
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: mysql
          MYSQL_USER: mysql
          MYSQL_PASSWORD: mysql
          MYSQL_HOST: 127.0.0.1
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: setup Go environment
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: "go.mod"
          cache-dependency-path: "go.sum"
      - name: Test
        run: go test -v ./...
      - name: Integration tests
        run: go test -v ./...
        env:
          INTEGRATION_TESTS: "true"
          MYSQL_URL: "mysql:mysql@tcp(127.0.0.1:3306)/mysql"
