name: ci
on:
  pull_request:
  push:
    branches:
      - main
permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:9.7@sha256:8fdf311514c91fa5014e93e98e19d7f5d9eb162a462c13100c956dacc278ee21
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: mysql
          MYSQL_USER: mysql
          MYSQL_PASSWORD: mysql
          MYSQL_HOST: 127.0.0.1
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: setup Go environment
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: "go.mod"
          cache-dependency-path: "go.sum"
      - name: Test
        run: go test -v ./...
      - name: Integration tests
        run: go test -v ./...
        env:
          INTEGRATION_TESTS: "true"
          MYSQL_URL: "mysql:mysql@tcp(127.0.0.1:3306)/mysql"
